# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Util-Any
version:      0.04
version_from: lib/Util/Any.pm
installdirs:  site
requires:
    Clone:                         0
    Data::Dumper:                  0
    ExportTo:                      0
    Hash::Util:                    0
    List::MoreUtils:               0
    List::Util:                    0
    Scalar::Util:                  0
    String::CamelCase:             0
    String::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
